de_project:
  outputs:
    dev:
      dataset: staging
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/tamdang/Desktop/week1_basic_setup/terrademo/keys/my-creds.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: bold-artifact-360712
      threads: 4
      type: bigquery
  target: dev
