version: '3'

services:
  # Database PostgreSQL cho Airflow
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Airflow
  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./de_project:/opt/airflow/de_project
      - ./entrypoint.sh:/opt/airflow/entrypoint.sh
    ports:
      - "8080:8080"
    entrypoint: /opt/airflow/entrypoint.sh 

  # Metabase
  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
